In [12]:
#Import necessary modules
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import os
from pyspark.sql import SparkSession

In [34]:
db_pass = os.environ.get('AZURE_DB_PASSWORD')
url = f'postgresql://levent:{db_pass}@euroleaguedb.postgres.database.azure.com/postgres?sslmode=require'

In [48]:
import findspark
findspark.init()

In [49]:
spark = SparkSession.builder.master(url).appName('euroleague').getOrCreate()

KeyboardInterrupt:

In [37]:
#Create sql enginge with sqlalchemy
engine = create_engine(url)

In [41]:
from sqlalchemy import MetaData
m = MetaData()
m.reflect(engine)
for table in m.tables.values():
    print(table.name)
    for column in table.c:
        print(column.name)

player_info
name
team
Nationality
Height
Born
pic_link
blank

In [40]:
pd.read_csv('player_info.csv').to_sql('player_info', engine, schema='public', index=False)

301

In [ ]:
pd.read_csv('player_info.csv')

In [23]:
pd.read_csv('player_stats.csv')

,#,Player,Team,GP,GS,Min,PTS,2PM,2PA,2P%,...,DR,TR,AST,STL,TO,BLK,BLKA,FC,FD,PIR
0,1,MIROSLAV RADULJICA,CZV,3,1,13:30,3,0,2,0%,...,0,0,0,1,3,0,0,6,2,-7
1,2,GREGOR GLAS,PAR,1,0,7:54,0,0,0,0%,...,0,0,1,0,4,0,0,2,0,-6
2,2,DIMITRIS AGRAVANIS,PAO,4,0,34:40,3,1,9,11.1%,...,6,10,0,3,1,1,0,12,3,-6
3,4,EGEHAN ARNA,EFS,5,0,13:35,0,0,0,0%,...,0,0,1,0,0,0,0,3,0,-5
4,5,LUCAS MARÍ,VBC,3,0,9:12,0,0,0,0%,...,1,1,0,0,0,0,0,5,0,-4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,290,WALTER TAVARES,RMB,33,31,791:22,346,135,200,67.5%,...,128,214,51,30,72,75,11,103,101,545
290,291,DARIUS THOMPSON,BKN,33,32,880:41,416,111,198,56.1%,...,68,102,221,57,89,15,7,84,105,563
291,292,WILL CLYBURN,EFS,33,17,1099:59,559,119,242,49.2%,...,160,193,71,35,52,6,18,71,168,626
292,293,MATHIAS LESSORT,PAR,33,20,1002:21,402,146,211,69.2%,...,132,238,46,30,48,27,11,88,156,648
293,294,SASHA VEZENKOV,OLY,32,31,917:13,559,144,220,65.5%,...,170,223,59,30,30,8,7,45,89,700

In [24]:
pd.read_csv('team_stats.csv')

,Rank,Team,Games,PIR,Ave,Per40,PTS,FTM,FTA,FT%,...,OREB,DREB,AST,STL,BLK,BLKA,TO,FD,FC,Min
0,1,Olympiacos Piraeus,33,3386,102.6,102.6,2771,457,596,76.7%,...,317,781,719,256,69,65,425,686,609,1320:00
1,2,Real Madrid,33,3370,102.1,101.4,2815,544,676,80.5%,...,331,880,643,193,143,61,433,681,676,1330:00
2,3,Cazoo Baskonia Vitoria-Gasteiz,33,3265,98.9,98.2,2871,472,612,77.1%,...,347,790,654,234,93,81,366,670,698,1330:00
3,4,Anadolu Efes Istanbul,33,3146,95.3,94.6,2736,443,539,82.2%,...,264,784,522,206,95,81,365,669,585,1330:00
4,5,Partizan Mozzart Bet Belgrade,33,3092,93.7,93.0,2813,592,714,82.9%,...,302,688,475,213,83,73,374,749,692,1330:00
5,6,AS Monaco,33,3069,93.0,92.0,2760,569,757,75.2%,...,407,709,512,245,67,78,354,761,674,1335:00
6,7,FC Barcelona,33,3035,92.0,91.3,2666,461,580,79.5%,...,345,778,636,191,64,69,420,677,714,1330:00
7,8,Fenerbahce Beko Istanbul,33,3016,91.4,90.7,2774,400,563,71.0%,...,377,729,592,216,56,80,392,671,690,1330:00
8,9,Maccabi Playtika Tel Aviv,33,2992,90.7,90.7,2741,431,537,80.3%,...,393,759,539,224,104,69,367,616,715,1320:00
9,10,ALBA Berlin,33,2906,88.1,87.4,2635,413,537,76.9%,...,391,796,652,224,105,102,484,628,655,1330:00
10,11,Valencia Basket,33,2823,85.5,84.9,2711,468,570,82.1%,...,324,714,579,216,54,83,437,667,733,1330:00
11,12,Virtus Segafredo Bologna,33,2803,84.9,84.6,2564,476,595,80.0%,...,269,753,638,234,69,82,487,656,692,1325:00
12,13,Panathinaikos Athens,33,2744,83.2,81.9,2615,532,717,74.2%,...,321,741,483,216,77,76,389,732,680,1340:00
13,14,Crvena Zvezda Meridianbet Belgrade,33,2706,82.0,81.4,2535,454,587,77.3%,...,346,739,559,217,55,87,411,662,704,1330:00
14,15,EA7 Emporio Armani Milan,33,2666,80.8,80.2,2459,414,537,77.1%,...,289,786,533,202,66,66,406,644,667,1330:00
15,16,Zalgiris Kaunas,33,2656,80.5,80.5,2508,460,582,79.0%,...,375,739,464,199,87,98,432,661,674,1320:00
16,17,FC Bayern Munich,33,2562,77.6,77.6,2525,492,601,81.9%,...,382,749,453,209,75,98,382,677,731,1320:00
17,18,LDLC ASVEL Villeurbanne,33,2473,74.9,74.9,2456,430,554,77.6%,...,292,710,477,215,69,81,453,660,700,1320:00

In [25]:
pd.read_csv('team_standings.csv')

,Position,Club,GP,Won,Lost,Win%,PTS+,PTS-,+/-,H,A,OT,L10
0,1,Olympiacos Piraeus *,33,23,10,69.7%,2771,2500,271,13-3,10-7,0-0,7-3
1,2,Real Madrid *,33,23,10,69.7%,2791,2580,211,13-4,10-6,1-1,7-3
2,3,FC Barcelona *,33,22,11,66.7%,2638,2509,129,12-4,10-7,1-1,7-3
3,4,AS Monaco *,33,21,12,63.6%,2730,2662,68,13-4,8-8,2-1,7-3
4,5,Fenerbahce Beko Istanbul,33,19,14,57.6%,2744,2666,78,12-5,7-9,2-0,5-5
5,6,Partizan Mozzart Bet Belgrade *,33,19,14,57.6%,2794,2700,94,11-5,8-9,0-2,7-3
6,7,Maccabi Playtika Tel Aviv *,33,19,14,57.6%,2741,2657,84,14-2,5-12,0-0,7-3
7,8,Cazoo Baskonia Vitoria-Gasteiz,33,18,15,54.5%,2841,2750,91,14-3,4-12,2-0,5-5
8,9,Zalgiris Kaunas,33,18,15,54.5%,2508,2546,-38,13-4,5-11,0-0,6-4
9,10,Crvena Zvezda Meridianbet Belgrade,33,16,17,48.5%,2512,2534,-22,10-6,6-11,1-1,6-4
10,11,Anadolu Efes Istanbul,33,16,17,48.5%,2713,2664,49,10-6,6-11,0-2,5-5
11,12,EA7 Emporio Armani Milan,33,15,18,45.5%,2450,2522,-72,9-8,6-10,0-2,7-3
12,13,Valencia Basket,33,15,18,45.5%,2685,2806,-121,9-8,6-10,2-0,3-7
13,14,Virtus Segafredo Bologna,33,13,20,39.4%,2555,2717,-162,8-8,5-12,0-1,2-8
14,15,FC Bayern Munich,33,11,22,33.3%,2525,2656,-131,8-8,3-14,0-0,2-8
15,16,Panathinaikos Athens,33,11,22,33.3%,2568,2690,-122,8-9,3-13,2-2,3-7
16,17,ALBA Berlin,33,10,23,30.3%,2616,2780,-164,5-11,5-12,1-1,4-6
17,18,LDLC ASVEL Villeurbanne,33,8,25,24.2%,2456,2699,-243,4-13,4-12,0-0,0-10